### ISSUE TITLE
False positive error with initcheck and managed memory

### ISSUE THREAD

**Issue by aborzunov** [NVIDIA/compute-sanitizer-samples#14] opened 2022-10-04 12:47 UTC
```C++
#include <algorithm>
#include <functional>

#include <thrust/execution_policy.h>
#include <thrust/functional.h>
#include <thrust/logical.h>

int main ()
{
    constexpr auto size = 100ul;
    constexpr auto value = 2;
    using dtype = int;
    dtype * d = nullptr;
    auto code = cudaMallocManaged(&d, sizeof(dtype) * size);
    if (code != cudaSuccess) {exit(1);}

    std::fill(d, d + size, value);

    auto rtr_code = false;
    rtr_code += not std::all_of(d, d + size, [=] (auto x) {return x == value;});
    rtr_code += not thrust::all_of(thrust::device, d, d + size, thrust::placeholders::_1 == value);

    cudaFree(d);

    return rtr_code;
}
```

```bash
$ nvcc main.cu -g -G
$ compute-sanitizer --tool initcheck a.out



========= COMPUTE-SANITIZER
========= Host API memory access error at host access to 0x7f14c9e00200 of size 16 bytes
=========     Uninitialized access at 0x7f14c9e00200 on access by cudaMemcopy source
=========     Saved host backtrace up to driver entry point at error
=========     Host Frame: [0x2e29d9]
=========                in /lib/x86_64-linux-gnu/libcuda.so.1
=========     Host Frame:__cudart606 [0x58b99]
=========                in /tmp/nvsanitize/a.out
=========     Host Frame:__cudart743 [0x278fd]
=========                in /tmp/nvsanitize/a.out
=========     Host Frame:cudaMemcpyAsync [0x7dd02]
=========                in /tmp/nvsanitize/a.out
=========     Host Frame:/usr/local/cuda/bin/../targets/x86_64-linux/include/thrust/system/cuda/detail/internal/copy_cross_system.h:192:thrust::tuple<bool, long, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type>* thrust::cuda_cub::__copy::cross_system_copy_n<thrust::cuda_cub::par_t, thrust::system::cpp::detail::tag, thrust::tuple<bool, long, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type>*, long, thrust::tuple<bool, long, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type>*>(thrust::cuda_cub::execution_policy<thrust::cuda_cub::par_t>&, thrust::system::cpp::detail::execution_policy<thrust::system::cpp::detail::tag>&, thrust::tuple<bool, long, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type>*, long, thrust::tuple<bool, long, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type>*, thrust::detail::integral_constant<bool, false>) [0x1bb81]
=========                in /tmp/nvsanitize/a.out
=========     Host Frame:/usr/local/cuda/bin/../targets/x86_64-linux/include/thrust/system/cuda/detail/internal/copy_cross_system.h:223:thrust::tuple<bool, long, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type>* thrust::cuda_cub::__copy::cross_system_copy_n<thrust::cuda_cub::par_t, thrust::system::cpp::detail::tag, thrust::tuple<bool, long, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type>*, long, thrust::tuple<bool, long, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type>*>(thrust::cuda_cub::cross_system<thrust::cuda_cub::par_t, thrust::system::cpp::detail::tag>, thrust::tuple<bool, long, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type>*, long, thrust::tuple<bool, long, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type>*) [0x1b5c4]
=========                in /tmp/nvsanitize/a.out
=========     Host Frame:/usr/local/cuda/bin/../targets/x86_64-linux/include/thrust/system/cuda/detail/internal/copy_cross_system.h:239:thrust::tuple<bool, long, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type>* thrust::cuda_cub::__copy::cross_system_copy<thrust::cuda_cub::par_t, thrust::system::cpp::detail::tag, thrust::tuple<bool, long, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type>*, thrust::tuple<bool, long, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type>*>(thrust::cuda_cub::cross_system<thrust::cuda_cub::par_t, thrust::system::cpp::detail::tag>, thrust::tuple<bool, long, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type>*, thrust::tuple<bool, long, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type>*, thrust::tuple<bool, long, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type>*) [0x1b15b]
=========                in /tmp/nvsanitize/a.out
=========     Host Frame:/usr/local/cuda/bin/../targets/x86_64-linux/include/thrust/system/cuda/detail/copy.h:176:thrust::tuple<bool, long, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type>* thrust::cuda_cub::copy<thrust::cuda_cub::par_t, thrust::system::cpp::detail::tag, thrust::tuple<bool, long, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type>*, thrust::tuple<bool, long, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type>*>(thrust::cuda_cub::cross_system<thrust::cuda_cub::par_t, thrust::system::cpp::detail::tag>, thrust::tuple<bool, long, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type>*, thrust::tuple<bool, long, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type>*, thrust::tuple<bool, long, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type>*) [0x1ae12]
=========                in /tmp/nvsanitize/a.out
=========     Host Frame:/usr/local/cuda/bin/../targets/x86_64-linux/include/thrust/system/cuda/detail/assign_value.h:75:thrust::cuda_cub::assign_value<thrust::system::cpp::detail::tag, thrust::cuda_cub::par_t, thrust::tuple<bool, long, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type>*, thrust::tuple<bool, long, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type>*>(thrust::cuda_cub::cross_system<thrust::system::cpp::detail::tag, thrust::cuda_cub::par_t>&, thrust::tuple<bool, long, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type>*, thrust::tuple<bool, long, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type>*)::war_nvbugs_881631::host_path(thrust::cuda_cub::cross_system<thrust::system::cpp::detail::tag, thrust::cuda_cub::par_t>&, thrust::tuple<bool, long, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type>*, thrust::tuple<bool, long, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type>*) [0x1aa6d]
=========                in /tmp/nvsanitize/a.out
=========     Host Frame:/usr/local/cuda/bin/../targets/x86_64-linux/include/thrust/system/cuda/detail/assign_value.h:95:void thrust::cuda_cub::assign_value<thrust::system::cpp::detail::tag, thrust::cuda_cub::par_t, thrust::tuple<bool, long, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type>*, thrust::tuple<bool, long, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type>*>(thrust::cuda_cub::cross_system<thrust::system::cpp::detail::tag, thrust::cuda_cub::par_t>&, thrust::tuple<bool, long, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type>*, thrust::tuple<bool, long, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type>*) [0x1aab3]
=========                in /tmp/nvsanitize/a.out
=========     Host Frame:/usr/local/cuda/bin/../targets/x86_64-linux/include/thrust/system/cuda/detail/get_value.h:55:thrust::cuda_cub::(anonymous namespace)::get_value_msvc2005_war<thrust::cuda_cub::par_t, thrust::tuple<bool, long, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type>*>(thrust::cuda_cub::execution_policy<thrust::cuda_cub::par_t>&, thrust::tuple<bool, long, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type>*)::war_nvbugs_881631::host_path(thrust::cuda_cub::execution_policy<thrust::cuda_cub::par_t>&, thrust::tuple<bool, long, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type>*) [0x1a56b]
=========                in /tmp/nvsanitize/a.out
=========     Host Frame:/usr/local/cuda/bin/../targets/x86_64-linux/include/thrust/system/cuda/detail/get_value.h:77:thrust::iterator_value<thrust::tuple<bool, long, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type>*>::type thrust::cuda_cub::(anonymous namespace)::get_value_msvc2005_war<thrust::cuda_cub::par_t, thrust::tuple<bool, long, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type>*>(thrust::cuda_cub::execution_policy<thrust::cuda_cub::par_t>&, thrust::tuple<bool, long, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type>*) [0x1a5bd]
=========                in /tmp/nvsanitize/a.out
=========     Host Frame:/usr/local/cuda/bin/../targets/x86_64-linux/include/thrust/system/cuda/detail/get_value.h:91:thrust::iterator_value<thrust::tuple<bool, long, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type>*>::type thrust::cuda_cub::get_value<thrust::cuda_cub::par_t, thrust::tuple<bool, long, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type>*>(thrust::cuda_cub::execution_policy<thrust::cuda_cub::par_t>&, thrust::tuple<bool, long, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type>*) [0x1a171]
=========                in /tmp/nvsanitize/a.out
=========     Host Frame:/usr/local/cuda/bin/../targets/x86_64-linux/include/thrust/system/cuda/detail/reduce.h:1022:thrust::tuple<bool, long, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type> thrust::cuda_cub::reduce_n<thrust::cuda_cub::par_t, thrust::zip_iterator<thrust::tuple<thrust::cuda_cub::transform_input_iterator_t<bool, int*, thrust::detail::unary_negate<thrust::detail::functional::actor<thrust::detail::functional::composite<thrust::detail::functional::transparent_binary_operator<thrust::equal_to<void> >, thrust::detail::functional::actor<thrust::detail::functional::argument<0u> >, thrust::detail::functional::value<int>, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type> > > >, thrust::cuda_cub::counting_iterator_t<long>, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type> >, long, thrust::tuple<bool, long, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type>, thrust::cuda_cub::__find_if::functor<thrust::tuple<bool, long, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type> > >(thrust::cuda_cub::execution_policy<thrust::cuda_cub::par_t>&, thrust::zip_iterator<thrust::tuple<thrust::cuda_cub::transform_input_iterator_t<bool, int*, thrust::detail::unary_negate<thrust::detail::functional::actor<thrust::detail::functional::composite<thrust::detail::functional::transparent_binary_operator<thrust::equal_to<void> >, thrust::detail::functional::actor<thrust::detail::functional::argument<0u> >, thrust::detail::functional::value<int>, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type> > > >, thrust::cuda_cub::counting_iterator_t<long>, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type> >, long, thrust::tuple<bool, long, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type>, thrust::cuda_cub::__find_if::functor<thrust::tuple<bool, long, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type> >) [0x16da4]
=========                in /tmp/nvsanitize/a.out
=========     Host Frame:/usr/local/cuda/bin/../targets/x86_64-linux/include/thrust/system/cuda/detail/reduce.h:1042:thrust::tuple<bool, long, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type> thrust::cuda_cub::reduce<thrust::cuda_cub::par_t, thrust::zip_iterator<thrust::tuple<thrust::cuda_cub::transform_input_iterator_t<bool, int*, thrust::detail::unary_negate<thrust::detail::functional::actor<thrust::detail::functional::composite<thrust::detail::functional::transparent_binary_operator<thrust::equal_to<void> >, thrust::detail::functional::actor<thrust::detail::functional::argument<0u> >, thrust::detail::functional::value<int>, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type> > > >, thrust::cuda_cub::counting_iterator_t<long>, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type> >, thrust::tuple<bool, long, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type>, thrust::cuda_cub::__find_if::functor<thrust::tuple<bool, long, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type> > >(thrust::cuda_cub::execution_policy<thrust::cuda_cub::par_t>&, thrust::zip_iterator<thrust::tuple<thrust::cuda_cub::transform_input_iterator_t<bool, int*, thrust::detail::unary_negate<thrust::detail::functional::actor<thrust::detail::functional::composite<thrust::detail::functional::transparent_binary_operator<thrust::equal_to<void> >, thrust::detail::functional::actor<thrust::detail::functional::argument<0u> >, thrust::detail::functional::value<int>, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type> > > >, thrust::cuda_cub::counting_iterator_t<long>, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type> >, thrust::zip_iterator<thrust::tuple<thrust::cuda_cub::transform_input_iterator_t<bool, int*, thrust::detail::unary_negate<thrust::detail::functional::actor<thrust::detail::functional::composite<thrust::detail::functional::transparent_binary_operator<thrust::equal_to<void> >, thrust::detail::functional::actor<thrust::detail::functional::argument<0u> >, thrust::detail::functional::value<int>, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type> > > >, thrust::cuda_cub::counting_iterator_t<long>, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type> >, thrust::tuple<bool, long, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type>, thrust::cuda_cub::__find_if::functor<thrust::tuple<bool, long, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type> >) [0x10a63]
=========                in /tmp/nvsanitize/a.out
=========     Host Frame:/usr/local/cuda/bin/../targets/x86_64-linux/include/thrust/system/cuda/detail/find.h:156:int* thrust::cuda_cub::find_if_n<thrust::cuda_cub::par_t, int*, long, thrust::detail::unary_negate<thrust::detail::functional::actor<thrust::detail::functional::composite<thrust::detail::functional::transparent_binary_operator<thrust::equal_to<void> >, thrust::detail::functional::actor<thrust::detail::functional::argument<0u> >, thrust::detail::functional::value<int>, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type> > > >(thrust::cuda_cub::execution_policy<thrust::cuda_cub::par_t>&, int*, long, thrust::detail::unary_negate<thrust::detail::functional::actor<thrust::detail::functional::composite<thrust::detail::functional::transparent_binary_operator<thrust::equal_to<void> >, thrust::detail::functional::actor<thrust::detail::functional::argument<0u> >, thrust::detail::functional::value<int>, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type> > >) [0x106ae]
=========                in /tmp/nvsanitize/a.out
=========     Host Frame:/usr/local/cuda/bin/../targets/x86_64-linux/include/thrust/system/cuda/detail/find.h:183:int* thrust::cuda_cub::find_if<thrust::cuda_cub::par_t, int*, thrust::detail::unary_negate<thrust::detail::functional::actor<thrust::detail::functional::composite<thrust::detail::functional::transparent_binary_operator<thrust::equal_to<void> >, thrust::detail::functional::actor<thrust::detail::functional::argument<0u> >, thrust::detail::functional::value<int>, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type> > > >(thrust::cuda_cub::execution_policy<thrust::cuda_cub::par_t>&, int*, int*, thrust::detail::unary_negate<thrust::detail::functional::actor<thrust::detail::functional::composite<thrust::detail::functional::transparent_binary_operator<thrust::equal_to<void> >, thrust::detail::functional::actor<thrust::detail::functional::argument<0u> >, thrust::detail::functional::value<int>, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type> > >) [0x103e5]
=========                in /tmp/nvsanitize/a.out
=========     Host Frame:/usr/local/cuda/bin/../targets/x86_64-linux/include/thrust/detail/find.inl:53:int* thrust::find_if<thrust::cuda_cub::par_t, int*, thrust::detail::unary_negate<thrust::detail::functional::actor<thrust::detail::functional::composite<thrust::detail::functional::transparent_binary_operator<thrust::equal_to<void> >, thrust::detail::functional::actor<thrust::detail::functional::argument<0u> >, thrust::detail::functional::value<int>, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type> > > >(thrust::detail::execution_policy_base<thrust::cuda_cub::par_t> const&, int*, int*, thrust::detail::unary_negate<thrust::detail::functional::actor<thrust::detail::functional::composite<thrust::detail::functional::transparent_binary_operator<thrust::equal_to<void> >, thrust::detail::functional::actor<thrust::detail::functional::argument<0u> >, thrust::detail::functional::value<int>, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type> > >) [0x10308]
=========                in /tmp/nvsanitize/a.out
=========     Host Frame:/usr/local/cuda/bin/../targets/x86_64-linux/include/thrust/system/detail/generic/logical.h:38:bool thrust::system::detail::generic::all_of<thrust::cuda_cub::par_t, int*, thrust::detail::functional::actor<thrust::detail::functional::composite<thrust::detail::functional::transparent_binary_operator<thrust::equal_to<void> >, thrust::detail::functional::actor<thrust::detail::functional::argument<0u> >, thrust::detail::functional::value<int>, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type> > >(thrust::execution_policy<thrust::cuda_cub::par_t>&, int*, int*, thrust::detail::functional::actor<thrust::detail::functional::composite<thrust::detail::functional::transparent_binary_operator<thrust::equal_to<void> >, thrust::detail::functional::actor<thrust::detail::functional::argument<0u> >, thrust::detail::functional::value<int>, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type> >) [0x10141]
=========                in /tmp/nvsanitize/a.out
=========     Host Frame:/usr/local/cuda/bin/../targets/x86_64-linux/include/thrust/detail/logical.inl:37:bool thrust::all_of<thrust::cuda_cub::par_t, int*, thrust::detail::functional::actor<thrust::detail::functional::composite<thrust::detail::functional::transparent_binary_operator<thrust::equal_to<void> >, thrust::detail::functional::actor<thrust::detail::functional::argument<0u> >, thrust::detail::functional::value<int>, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type> > >(thrust::detail::execution_policy_base<thrust::cuda_cub::par_t> const&, int*, int*, thrust::detail::functional::actor<thrust::detail::functional::composite<thrust::detail::functional::transparent_binary_operator<thrust::equal_to<void> >, thrust::detail::functional::actor<thrust::detail::functional::argument<0u> >, thrust::detail::functional::value<int>, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type> >) [0xfc9a]
=========                in /tmp/nvsanitize/a.out
=========     Host Frame:/tmp/nvsanitize/main.cu:21:main [0xc2c2]
=========                in /tmp/nvsanitize/a.out
=========     Host Frame:../csu/libc-start.c:342:__libc_start_main [0x24083]
=========                in /lib/x86_64-linux-gnu/libc.so.6
=========     Host Frame:_start [0xc0ee]
=========                in /tmp/nvsanitize/a.out
=========
========= ERROR SUMMARY: 1 error
```

While nvprof detects page page faults, and, hence, unified memory system handles data transfers and it is correct code?

**Comment by aladram** [comment] 2022-10-10 22:41
Thank you reporting this issue, and for your patience! This is indeed a false positive error and therefore a compute-sanitizer bug. I will work on a fix as soon as possible, and keep you updated. Please don't hesitate to ping me here if you have any question.

**Comment by aladram** [comment] 2022-10-31 18:32
Quick update on this: we are still working on resolution for this issue, and made significant progress in identifying the root cause of this issue.

**Comment by aladram** [comment] 2022-11-04 19:32
I will close this bug as will not fix because the issue we identified internally is slightly different, and happens without flag `-G`. The issue you are facing is described in the "Known Issues" section of compute-sanitizer documentation: https://docs.nvidia.com/compute-sanitizer/ReleaseNotes/index.html#known-issues. Please feel free to ignore this error report as it only reflects the fact that, internally, thrust is copying a structure whose padding is not initialized on device memory (for performance reasons) and later copied in host memory. It is a false positive because said padding is not actually used on the host side. Hope that helps! Please let me know if you have any question.

**Closed as completed by aladram** 2022-11-04 19:32 UTC
