### ISSUE TITLE
Sanitizer bug reproducer

### ISSUE THREAD

**Issue by Jokeren** [NVIDIA/compute-sanitizer-samples#7] opened 2019-08-21 15:10 UTC
Hi @achartier , I created a repo for reproducing some bugs with compute sanitizer. Could you please try it out?

https://github.com/Jokeren/sanitizer-bug-reproducer

I will add samples to this repo if I find other problems later. Currently, I notice that even a patch without any real code causes problems for some samples.

Is it possible to launch a telecon between your team and us? I would like to share our use cases, provide some feedbacks, and know a little bit more about your plans.

Are you a member of CUPTI team? We have a long-term collaboration with CUPTI team. Otherwise, the telecon may needs some approval as I know NVIDIA does not allow engineers to connect directly with people from outside.

**Comment by achartier** [comment] 2019-08-21 15:57
Hi @Jokeren ,

I will try to look into these issues as soon as possible. Apologies for the delays.

I am not a member of the CUPTI team. However, I started an internal discussion on setting up a telecon and hope to have more news soon.

**Comment by Jokeren** [comment] 2019-08-21 16:24
Thank you for your effort!

**Comment by achartier** [comment] 2019-08-22 01:35
I was able to reproduce the bug locally and fix it. Thanks for the repro, it was very useful.

Could you also add the code you were using for issue #4?

**Comment by Jokeren** [comment] 2019-08-22 02:35
Sure, I will add a sample and let you know.

**Comment by Jokeren** [comment] 2019-08-22 23:24
Hi @achartier,

I found it hard to reproduce the previous bug as I forgot the exact patch I wrote...

Sorry about that. If I discover this bug again, I will let you know.

**Comment by Jokeren** [comment] 2019-09-03 02:48
Hi @achartier, is there any update for the telecon on your side?

We are eager to try out the version you fixed without bugs. Is it possible for us to use an internal version before the next CUDA release?

**Comment by achartier** [comment] 2021-09-07 23:47
This has been fixed since then, closing.

**Closed as completed by achartier** 2021-09-07 23:47 UTC
